# Generated by Django 4.1.5 on 2023-02-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_cart_userid_wishlist_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='productimage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='productimage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='productimage',
            field=models.ImageField(upload_to=''),
        ),
    ]
